name: Flutter CI (PROYECTO FINAL)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Version de flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0' # correccion de version de flutter          

      - name: Instalar dependencias
        run: flutter pub get

      - name: correr amalizador
        run: flutter analyze

      - name: Correr prubas
        run: flutter test
      - name: Análisis de código
        run: flutter analyze --no-fatal-infos


